language: objective-c

# Handle git submodules yourself
# http://stackoverflow.com/a/24600210/805882
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - ./Submodules/OnionKit/build-libssl.sh --noverify
  - ./Submodules/OnionKit/build-libevent.sh --noverify
  - ./Submodules/OnionKit/build-tor.sh --noverify
  - ./Submodules/OTRKit/build-all.sh

before_script:
  - gem install cocoapods
  - brew update
  - brew upgrade xctool
script:
  - xctool -workspace ChatSecure.xcworkspace -scheme ChatSecure -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO build

notifications:
  email: false
