osx_image: xcode7.3
language: objective-c

# Handle git submodules yourself
# http://stackoverflow.com/a/24600210/805882
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - bundle install # We still need CocoaPods 0.39.0
    - sed -i -e 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - sed -i -e 's/git@github.com:/git:\/\/github.com\//' Podfile
    - git submodule update --init --recursive

install:
  - cp OTRResources/Secrets-template.plist OTRResources/Secrets.plist
  - cp configurations/OTR_Codesigning.xcconfig.sample configurations/OTR_Codesigning.xcconfig
  - git clone https://github.com/ChatSecure/ChatSecure-iOS-Precompiled-Dependencies.git
  - unzip -q ./ChatSecure-iOS-Precompiled-Dependencies/CPAProxyDependencies.zip -d ./Submodules/CPAProxy/
  - unzip -q ./ChatSecure-iOS-Precompiled-Dependencies/OTRKitDependencies.zip -d ./Submodules/OTRKit/
  - unzip -q ./ChatSecure-iOS-Precompiled-Dependencies/Pods.zip
  # We use precompiled dependencies for tests now
  #- export ARCHS="i386"   # Only build CPAProxy dependencies for i386 to speed things up
  #- bash ./Submodules/CPAProxy/scripts/build-all.sh
  #- bash ./Submodules/OTRKit/scripts/build-all.sh

before_script:
  - export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=1 # https://github.com/CocoaPods/CocoaPods/issues/3850
  - bundle exec pod install
script:
  - xctool -workspace ChatSecure.xcworkspace -scheme ChatSecureTests -sdk iphonesimulator -arch i386 test
