osx_image: xcode8
language: objective-c

# Handle git submodules yourself
# http://stackoverflow.com/a/24600210/805882
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - bundle install # We need a pre-release CocoaPods version "1.1.0.rc.1"
    - sed -i -e 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - sed -i -e 's/git@github.com:/git:\/\/github.com\//' Podfile
    - git submodule update --init --recursive

install:
  - cp OTRResources/Secrets-template.plist OTRResources/Secrets.plist
  - cp configurations/OTR_Codesigning.xcconfig.sample configurations/OTR_Codesigning.xcconfig
  - git clone https://github.com/ChatSecure/ChatSecure-iOS-Precompiled-Dependencies.git
  - unzip -q ./ChatSecure-iOS-Precompiled-Dependencies/CPAProxyDependencies.zip -d ./Submodules/CPAProxy/
  - unzip -q ./ChatSecure-iOS-Precompiled-Dependencies/OTRKitDependencies.zip -d ./Submodules/OTRKit/
  - unzip -q ./ChatSecure-iOS-Precompiled-Dependencies/Pods.zip

before_script:
  - export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=1 # https://github.com/CocoaPods/CocoaPods/issues/3850
  - bundle exec pod repo update --silent
  - bundle exec pod install
  - bundle exec pod update libsqlfs SQLCipher --no-repo-update # Waiting for CocoaPods fix https://github.com/CocoaPods/CocoaPods/pull/5844
script:
  - set -o pipefail
  - xcodebuild -workspace ChatSecure.xcworkspace -scheme ChatSecureTests -sdk iphonesimulator -destination 'name=iPhone 6' test | xcpretty -c